/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exception_Handling_Assignment;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
